server:
  port: 8084
spring:
  application:
    name: ride-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    url: jdbc:postgresql://localhost:5432/ride_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
eureka:
  instance:
    hostname: ride-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
