server:
  port: 8084
spring:
  application:
    name: ride-service
  r2dbc:
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    url: r2dbc:postgresql://localhost:5432/ride_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    url: jdbc:postgresql://localhost:5432/ride_db
    change-log: classpath:/db/changelog/db.changelog-master.xml
    password: ${POSTGRESQL_PASSWORD}
    user: ${POSTGRESQL_USERNAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/cab-aggregator-realm
          jwk-set-uri: http://localhost:8100/realms/cab-aggregator-realm/protocol/openid-connect/certs
eureka:
  instance:
    hostname: ride-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
